import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header";
import LeftSideBar from "@/components/shared/left-side-bar";
import RightSideBar from "@/components/shared/right-side-bar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          {/* Header */}
          <Header />
          <main className="flex flex-row">
            {/* LeftSidebar */}
            <LeftSideBar />
            <section className="main-container">
              <div className="w-full max-w-4xl">{children}</div>
            </section>
            {/* Rightsidebar */}
            <RightSideBar />
          </main>
          {/* Footer */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
